version: '3.12'

services:
  web:
    build: .
    command: gunicorn TrackSpot.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media  # Map your local media directory
      - ./static:/app/static  # Map your local static directory
    ports:
      - "80:80"
    depends_on:
      - web
