version: '3.12'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 3 TrackSpot.wsgi:application
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    env_file:
      - .env

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
