# Generated by Django 5.0.3 on 2024-06-26 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
