# Generated by Django 5.0.3 on 2024-06-26 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0002_alter_websiteuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiteuser',
            name='user',
        ),
    ]
