# Generated by Django 5.0.3 on 2024-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0002_ques_websiteuser_profile_image_claim_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='claimer',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='item',
        ),
        migrations.RemoveField(
            model_name='uploadeditem',
            name='claimed',
        ),
        migrations.RemoveField(
            model_name='uploadeditem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='uploadeditem',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='uploadeditem',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='uploadeditem',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploadeditem',
            name='image',
            field=models.ImageField(upload_to='uploaded_items/'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Ques',
        ),
        migrations.DeleteModel(
            name='Claim',
        ),
    ]
