# Generated by Django 5.0.3 on 2024-03-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0003_remove_claim_claimer_remove_claim_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeditem',
            name='image',
            field=models.ImageField(null=True, upload_to='uploaded_items/'),
        ),
    ]
