# Generated by Django 5.0.3 on 2024-03-24 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0004_alter_uploadeditem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeditem',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='lf.uploadeditem')),
            ],
        ),
    ]
