# Generated by Django 5.0.3 on 2024-03-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lf', '0008_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approver_phone_number',
            field=models.CharField(default='1234567897', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='approver_username',
            field=models.CharField(default='MYAdmin', max_length=100),
        ),
    ]
